  
  USE INTERPARK

  CREATE TABLE profile_pictures (
  id INT AUTO_INCREMENT PRIMARY KEY,
  img VARCHAR(255),
  class VARCHAR(255),
  user_id INT
);

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  xp INT DEFAULT 0
);

CREATE TABLE tricks (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL,
    video VARCHAR(255) NOT NULL,
    level VARCHAR(100) NOT NULL,
    xp INT NOT NULL
);

CREATE TABLE validated_tricks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  trick_id INT NOT NULL,
  is_validated BOOLEAN
);